// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/serlip06",
            "email": "714220023@std.ulbi.ac.id"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/customer": {
            "get": {
                "description": "Mengambil semua data customer.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer"
                ],
                "summary": "Get All Data Customer.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Customer"
                        }
                    }
                }
            }
        },
        "/customer/{id}": {
            "get": {
                "description": "Ambil per ID data customer.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer"
                ],
                "summary": "Get By ID Data Customer.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Masukan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Customer"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/insert": {
            "post": {
                "description": "Input data customer.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Customer"
                ],
                "summary": "Insert data customer.",
                "parameters": [
                    {
                        "description": "Payload Body [RAW]",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.ReqCustomer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Customer"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.Customer": {
            "type": "object",
            "properties": {
                "_id": {
                    "type": "string",
                    "example": "1234567"
                },
                "alamat": {
                    "type": "string",
                    "example": "jl.sarijadi"
                },
                "deskripsi": {
                    "type": "string",
                    "example": "nasi goreng dengan telor dan daging"
                },
                "email": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "Xaviera_89@gmail.com",
                        "Putri_90@gmail.com"
                    ]
                },
                "gambar": {
                    "type": "string",
                    "example": "https://i.pinimg.com/564x/94/82/ab/9482ab2e248d249e7daa7fd6924c8d3b.jpg"
                },
                "harga": {
                    "type": "integer",
                    "example": 15000
                },
                "nama": {
                    "type": "string",
                    "example": "xavieraa putri"
                },
                "nama_produk": {
                    "type": "string",
                    "example": "Nasi Goreng"
                },
                "phone_number": {
                    "type": "string",
                    "example": "085798654096"
                },
                "stok": {
                    "type": "string",
                    "example": "10"
                }
            }
        },
        "controller.ReqCustomer": {
            "type": "object",
            "properties": {
                "alamat": {
                    "type": "string",
                    "example": "jl.sarijadi"
                },
                "deskripsi": {
                    "type": "string",
                    "example": "nasi goreng dengan telor dan daging"
                },
                "email": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "Xaviera_89@gmail.com",
                        "Putri_90@gmail.com"
                    ]
                },
                "gambar": {
                    "type": "string",
                    "example": "https://i.pinimg.com/564x/94/82/ab/9482ab2e248d249e7daa7fd6924c8d3b.jpg"
                },
                "harga": {
                    "type": "integer",
                    "example": 15000
                },
                "nama": {
                    "type": "string",
                    "example": "Tes swager"
                },
                "nama_produk": {
                    "type": "string",
                    "example": "Nasi Goreng"
                },
                "phone_number": {
                    "type": "string",
                    "example": "085798654096"
                },
                "stok": {
                    "type": "string",
                    "example": "10"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "ats-714220023-serlipariela-38bba14820aa.herokuapp.com",
	BasePath:         "/",
	Schemes:          []string{"https", "http"},
	Title:            "TES SWAGGER ULBI",
	Description:      "This is a sample swagger for Fiber",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
