basePath: /
definitions:
  controller.Customer:
    properties:
      _id:
        type: string
      alamat:
        type: string
      deskripsi:
        type: string
      email:
        items:
          type: string
        type: array
      gambar:
        type: string
      harga:
        type: integer
      nama:
        type: string
      nama_produk:
        type: string
      phone_number:
        type: string
      stok:
        type: string
    type: object
host: ats-714220023-serlipariela-38bba14820aa.herokuapp.com
info:
  contact:
    email: 714220023@std.ulbi.ac.id
    name: API Support
    url: https://github.com/serlip06
  description: This is a sample swagger for Fiber
  title: TES SWAGGER ULBI
  version: "1.0"
paths:
  /customer:
    get:
      consumes:
      - application/json
      description: Mengambil semua data customer.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Customer'
      summary: Get All Data Customer.
      tags:
      - Customer
  /customer/{id}:
    get:
      consumes:
      - application/json
      description: Ambil per ID data customer.
      parameters:
      - description: Masukan ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.Customer'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get By ID Data Customer.
      tags:
      - Customer
schemes:
- https
- http
swagger: "2.0"
